# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gram.Profile'),
            preserve_default=False,
        ),
    ]
