# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-09 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20200209_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post_time',
        ),
    ]
