# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-09 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_remove_image_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 9, 9, 9, 30, 434469, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
