# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0006_auto_20200209_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
