# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-09 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0007_auto_20200209_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
