# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0011_remove_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gram.Profile'),
            preserve_default=False,
        ),
    ]
