# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-12 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0014_auto_20200212_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
